### ISSUE TITLE
Why call it DN-DETR rather than DN-DAB-DETR?

### ISSUE THREAD

**Issue by yeslogin2** [FengLi-ust/DN-DETR#4]
Glad to see the great work and excitedly awaiting the release of the code, but still got a concern:
Why call it DN-DETR rather than DN-DAB-DETR?
Since the main method of the paper was built upon DAB-DETR and the sota numbers were achieved based on the DAB-DETR, then I guess it should be called DN-DAB-DETR. The name DN-DETR sounds like the work was based on vanilla DETR without changing the original Transformer decoder. I saw that your experiments based on Deformable-DETR were called DN-Deformable-DETR, the name of DN-DETR becomes more misleading with respect to that.
And the paper said the code will be organized as a plugin-module that can be applied to any DETR-like models including vanilla DETR, so what should it be called when applying the denoising method to vanilla DETR? Also the result of that case seems didn't appear on the results table.
Many thanks

**Comment by FengLi-ust** [comment]
Thanks for this great question. We agree that DN-DAB-DETR is a great name to show that we base on DAB-DETR to do the denoising. We name it DN-DETR because denoising training is also helpful for other DETR-like models. The key insight is that certain "box information" flows in the DETR-like models, though in different formulations. DAB-DETR explicitly formulates this "box information" so it works well with denoising training. DAB is also one of the best models before DN-DETR, so we choose it as our base model.

In addition, DN can support other DETR-like models like Anchor DETR with 2D anchors and Vanilla DETR without anchors. For DN-Anchor-DETR, it can be easily modified to 4D anchors to achieve better results, we can also follow Anchor DETR to add noise only to the 2D anchors. For DN-Vanilla-DETR, we can simply use a linear box embedding to embed noised boxes into the same dimension as DETR queries. As Vanilla DETR do not explicitly have a content part and a position part, we can add the label embedding and box embedding together as DETR queries. Our preliminary results indicate that the convergence speed of such models also increases significantly. We will try to release these results in our final camera-ready version. Thank you.

**Comment by yeslogin2** [comment]
Thanks a lot for the detailed reply and explanation which helps greatly. Your excellent work inspires a lot on understanding and improving training procedures

**Comment by FengLi-ust** [comment]
Thank you. We recently release another work [DINO](https://arxiv.org/pdf/2203.03605.pdf) that for the first time establishes a DETR-like model as a SOTA model on the [leaderboard](https://paperswithcode.com/task/object-detection). You may also read it if you are interested.

**Comment by yeslogin2** [comment]
Great! That looks definitely interesting
